var KI4SO_SERVER_EC = "KI4SO_SERVER_EC";//登陆EC
var LOGIN_USER_NAME = "LOGIN_USER_NAME";//登陆名
var LOGIN_USER_PASS = "LOGIN_USER_PASS";//登陆密码
var PLATFORM_USER_OBJ = "userObj";//用户对象
var PLATFORM_USER_ID = "DataUserId";//用户ID
var PLATFORM_RESOURCE_CODES = "resourceCodes";//用户权限code
var STORE_BUY_GOODS = "STORE_BUY_GOODS";//门店购买物品
var STORE_BUY_TOTAL_PRICE = "STORE_BUY_TOTAL_PRICE";//门店购买物品总价
var ORDER_SERVICE_INFO = "ORDER_SERVICE_INFO";//服务信息
var ORDER_INVOICE_INFO = "ORDER_INVOICE_INFO";//发票信息
var CEMETERY_POSITION_MGFEE_DETAIL = "CEMETERY_POSITION_MGFEE_DETAIL";//墓位管理费信息
var AMATEUR_LEVEL = "amateurLevel";//非职业顾问等级
var GOODS_CHANNEL = "channel";//渠道ID

var ADVISTOR_BUY_GOODS = "STORE_BUY_GOODS";//门店购买物品
var ADVISTOR_TOTAL_PRICE = "STORE_BUY_TOTAL_PRICE";//门店购买物品总价

var GOODS_ORDER_SERVICE_INFO = "kehu";//单项服务信息
var GOODS_ORDER_INVOICE_INFO = "fapiao";//单项发票信息
var GOODS_ORDER_FORMDATA="formData";//提交商品


module.exports.KI4SO_SERVER_EC = KI4SO_SERVER_EC;
module.exports.PLATFORM_USER_OBJ = PLATFORM_USER_OBJ;
module.exports.PLATFORM_USER_ID = PLATFORM_USER_ID;
module.exports.PLATFORM_RESOURCE_CODES = PLATFORM_RESOURCE_CODES;
module.exports.STORE_BUY_GOODS = STORE_BUY_GOODS;
module.exports.STORE_BUY_TOTAL_PRICE = STORE_BUY_TOTAL_PRICE;
module.exports.ORDER_SERVICE_INFO = ORDER_SERVICE_INFO;
module.exports.ORDER_INVOICE_INFO = ORDER_INVOICE_INFO;
module.exports.LOGIN_USER_NAME = LOGIN_USER_NAME;
module.exports.LOGIN_USER_PASS = LOGIN_USER_PASS;
module.exports.CEMETERY_POSITION_MGFEE_DETAIL = CEMETERY_POSITION_MGFEE_DETAIL;
module.exports.AMATEUR_LEVEL = AMATEUR_LEVEL;
module.exports.GOODS_CHANNEL = GOODS_CHANNEL;
module.exports.GOODS_ORDER_SERVICE_INFO = GOODS_ORDER_SERVICE_INFO;
module.exports.GOODS_ORDER_INVOICE_INFO = GOODS_ORDER_INVOICE_INFO;
module.exports.GOODS_ORDER_FORMDATA = GOODS_ORDER_FORMDATA;